package com.fp.neezit.user.model.vo;

public class UserMasterQualifcation {
	private String USER_EMAIL; 
	private String MASTER_QUALIFICATION1;
	private String MASTER_QUALIFICATION1_PIC;
	private String MASTER_QUALIFICATION2;
	private String MASTER_QUALIFICATION2_PIC;
	private String MASTER_QUALIFICATION3;
	private String MASTER_QUALIFICATION3_PIC;
	private String MASTER_QUALIFICATION4;
	private String MASTER_QUALIFICATION4_PIC;
	private String MASTER_QUALIFICATION5;
	private String MASTER_QUALIFICATION5_PIC;
	public UserMasterQualifcation() {
		super();
		// TODO Auto-generated constructor stub
	}
	public UserMasterQualifcation(String uSER_EMAIL, String mASTER_QUALIFICATION1, String mASTER_QUALIFICATION1_PIC,
			String mASTER_QUALIFICATION2, String mASTER_QUALIFICATION2_PIC, String mASTER_QUALIFICATION3,
			String mASTER_QUALIFICATION3_PIC, String mASTER_QUALIFICATION4, String mASTER_QUALIFICATION4_PIC,
			String mASTER_QUALIFICATION5, String mASTER_QUALIFICATION5_PIC) {
		super();
		USER_EMAIL = uSER_EMAIL;
		MASTER_QUALIFICATION1 = mASTER_QUALIFICATION1;
		MASTER_QUALIFICATION1_PIC = mASTER_QUALIFICATION1_PIC;
		MASTER_QUALIFICATION2 = mASTER_QUALIFICATION2;
		MASTER_QUALIFICATION2_PIC = mASTER_QUALIFICATION2_PIC;
		MASTER_QUALIFICATION3 = mASTER_QUALIFICATION3;
		MASTER_QUALIFICATION3_PIC = mASTER_QUALIFICATION3_PIC;
		MASTER_QUALIFICATION4 = mASTER_QUALIFICATION4;
		MASTER_QUALIFICATION4_PIC = mASTER_QUALIFICATION4_PIC;
		MASTER_QUALIFICATION5 = mASTER_QUALIFICATION5;
		MASTER_QUALIFICATION5_PIC = mASTER_QUALIFICATION5_PIC;
	}
	public String getUSER_EMAIL() {
		return USER_EMAIL;
	}
	public void setUSER_EMAIL(String uSER_EMAIL) {
		USER_EMAIL = uSER_EMAIL;
	}
	public String getMASTER_QUALIFICATION1() {
		return MASTER_QUALIFICATION1;
	}
	public void setMASTER_QUALIFICATION1(String mASTER_QUALIFICATION1) {
		MASTER_QUALIFICATION1 = mASTER_QUALIFICATION1;
	}
	public String getMASTER_QUALIFICATION1_PIC() {
		return MASTER_QUALIFICATION1_PIC;
	}
	public void setMASTER_QUALIFICATION1_PIC(String mASTER_QUALIFICATION1_PIC) {
		MASTER_QUALIFICATION1_PIC = mASTER_QUALIFICATION1_PIC;
	}
	public String getMASTER_QUALIFICATION2() {
		return MASTER_QUALIFICATION2;
	}
	public void setMASTER_QUALIFICATION2(String mASTER_QUALIFICATION2) {
		MASTER_QUALIFICATION2 = mASTER_QUALIFICATION2;
	}
	public String getMASTER_QUALIFICATION2_PIC() {
		return MASTER_QUALIFICATION2_PIC;
	}
	public void setMASTER_QUALIFICATION2_PIC(String mASTER_QUALIFICATION2_PIC) {
		MASTER_QUALIFICATION2_PIC = mASTER_QUALIFICATION2_PIC;
	}
	public String getMASTER_QUALIFICATION3() {
		return MASTER_QUALIFICATION3;
	}
	public void setMASTER_QUALIFICATION3(String mASTER_QUALIFICATION3) {
		MASTER_QUALIFICATION3 = mASTER_QUALIFICATION3;
	}
	public String getMASTER_QUALIFICATION3_PIC() {
		return MASTER_QUALIFICATION3_PIC;
	}
	public void setMASTER_QUALIFICATION3_PIC(String mASTER_QUALIFICATION3_PIC) {
		MASTER_QUALIFICATION3_PIC = mASTER_QUALIFICATION3_PIC;
	}
	public String getMASTER_QUALIFICATION4() {
		return MASTER_QUALIFICATION4;
	}
	public void setMASTER_QUALIFICATION4(String mASTER_QUALIFICATION4) {
		MASTER_QUALIFICATION4 = mASTER_QUALIFICATION4;
	}
	public String getMASTER_QUALIFICATION4_PIC() {
		return MASTER_QUALIFICATION4_PIC;
	}
	public void setMASTER_QUALIFICATION4_PIC(String mASTER_QUALIFICATION4_PIC) {
		MASTER_QUALIFICATION4_PIC = mASTER_QUALIFICATION4_PIC;
	}
	public String getMASTER_QUALIFICATION5() {
		return MASTER_QUALIFICATION5;
	}
	public void setMASTER_QUALIFICATION5(String mASTER_QUALIFICATION5) {
		MASTER_QUALIFICATION5 = mASTER_QUALIFICATION5;
	}
	public String getMASTER_QUALIFICATION5_PIC() {
		return MASTER_QUALIFICATION5_PIC;
	}
	public void setMASTER_QUALIFICATION5_PIC(String mASTER_QUALIFICATION5_PIC) {
		MASTER_QUALIFICATION5_PIC = mASTER_QUALIFICATION5_PIC;
	}
	@Override
	public String toString() {
		return "MasterQualifcation [USER_EMAIL=" + USER_EMAIL + ", MASTER_QUALIFICATION1=" + MASTER_QUALIFICATION1
				+ ", MASTER_QUALIFICATION1_PIC=" + MASTER_QUALIFICATION1_PIC + ", MASTER_QUALIFICATION2="
				+ MASTER_QUALIFICATION2 + ", MASTER_QUALIFICATION2_PIC=" + MASTER_QUALIFICATION2_PIC
				+ ", MASTER_QUALIFICATION3=" + MASTER_QUALIFICATION3 + ", MASTER_QUALIFICATION3_PIC="
				+ MASTER_QUALIFICATION3_PIC + ", MASTER_QUALIFICATION4=" + MASTER_QUALIFICATION4
				+ ", MASTER_QUALIFICATION4_PIC=" + MASTER_QUALIFICATION4_PIC + ", MASTER_QUALIFICATION5="
				+ MASTER_QUALIFICATION5 + ", MASTER_QUALIFICATION5_PIC=" + MASTER_QUALIFICATION5_PIC + "]";
	}
	
	
}
