package com.fp.neezit.user.model.vo;

public class UserMasterQualifcation {
	private String USER_EMAIL; 
	private String MASTER_QUALIFICATION1;
	private String MASTER_QUALIFICATION1_PIC_ORI;
	private String MASTER_QUALIFICATION1_PIC_RE;
	private String MASTER_QUALIFICATION2;
	private String MASTER_QUALIFICATION2_PIC_ORI;
	private String MASTER_QUALIFICATION2_PIC_RE;
	private String MASTER_QUALIFICATION3;
	private String MASTER_QUALIFICATION3_PIC_ORI;
	private String MASTER_QUALIFICATION3_PIC_RE;
	private String MASTER_QUALIFICATION4;
	private String MASTER_QUALIFICATION4_PIC_ORI;
	private String MASTER_QUALIFICATION4_PIC_RE;
	private String MASTER_QUALIFICATION5;
	private String MASTER_QUALIFICATION5_PIC_ORI;
	private String MASTER_QUALIFICATION5_PIC_RE;
	public UserMasterQualifcation() {
		super();
		// TODO Auto-generated constructor stub
	}
	public UserMasterQualifcation(String uSER_EMAIL, String mASTER_QUALIFICATION1, String mASTER_QUALIFICATION1_PIC_ORI,
			String mASTER_QUALIFICATION1_PIC_RE, String mASTER_QUALIFICATION2, String mASTER_QUALIFICATION2_PIC_ORI,
			String mASTER_QUALIFICATION2_PIC_RE, String mASTER_QUALIFICATION3, String mASTER_QUALIFICATION3_PIC_ORI,
			String mASTER_QUALIFICATION3_PIC_RE, String mASTER_QUALIFICATION4, String mASTER_QUALIFICATION4_PIC_ORI,
			String mASTER_QUALIFICATION4_PIC_RE, String mASTER_QUALIFICATION5, String mASTER_QUALIFICATION5_PIC_ORI,
			String mASTER_QUALIFICATION5_PIC_RE) {
		super();
		USER_EMAIL = uSER_EMAIL;
		MASTER_QUALIFICATION1 = mASTER_QUALIFICATION1;
		MASTER_QUALIFICATION1_PIC_ORI = mASTER_QUALIFICATION1_PIC_ORI;
		MASTER_QUALIFICATION1_PIC_RE = mASTER_QUALIFICATION1_PIC_RE;
		MASTER_QUALIFICATION2 = mASTER_QUALIFICATION2;
		MASTER_QUALIFICATION2_PIC_ORI = mASTER_QUALIFICATION2_PIC_ORI;
		MASTER_QUALIFICATION2_PIC_RE = mASTER_QUALIFICATION2_PIC_RE;
		MASTER_QUALIFICATION3 = mASTER_QUALIFICATION3;
		MASTER_QUALIFICATION3_PIC_ORI = mASTER_QUALIFICATION3_PIC_ORI;
		MASTER_QUALIFICATION3_PIC_RE = mASTER_QUALIFICATION3_PIC_RE;
		MASTER_QUALIFICATION4 = mASTER_QUALIFICATION4;
		MASTER_QUALIFICATION4_PIC_ORI = mASTER_QUALIFICATION4_PIC_ORI;
		MASTER_QUALIFICATION4_PIC_RE = mASTER_QUALIFICATION4_PIC_RE;
		MASTER_QUALIFICATION5 = mASTER_QUALIFICATION5;
		MASTER_QUALIFICATION5_PIC_ORI = mASTER_QUALIFICATION5_PIC_ORI;
		MASTER_QUALIFICATION5_PIC_RE = mASTER_QUALIFICATION5_PIC_RE;
	}
	public String getUSER_EMAIL() {
		return USER_EMAIL;
	}
	public void setUSER_EMAIL(String uSER_EMAIL) {
		USER_EMAIL = uSER_EMAIL;
	}
	public String getMASTER_QUALIFICATION1() {
		return MASTER_QUALIFICATION1;
	}
	public void setMASTER_QUALIFICATION1(String mASTER_QUALIFICATION1) {
		MASTER_QUALIFICATION1 = mASTER_QUALIFICATION1;
	}
	public String getMASTER_QUALIFICATION1_PIC_ORI() {
		return MASTER_QUALIFICATION1_PIC_ORI;
	}
	public void setMASTER_QUALIFICATION1_PIC_ORI(String mASTER_QUALIFICATION1_PIC_ORI) {
		MASTER_QUALIFICATION1_PIC_ORI = mASTER_QUALIFICATION1_PIC_ORI;
	}
	public String getMASTER_QUALIFICATION1_PIC_RE() {
		return MASTER_QUALIFICATION1_PIC_RE;
	}
	public void setMASTER_QUALIFICATION1_PIC_RE(String mASTER_QUALIFICATION1_PIC_RE) {
		MASTER_QUALIFICATION1_PIC_RE = mASTER_QUALIFICATION1_PIC_RE;
	}
	public String getMASTER_QUALIFICATION2() {
		return MASTER_QUALIFICATION2;
	}
	public void setMASTER_QUALIFICATION2(String mASTER_QUALIFICATION2) {
		MASTER_QUALIFICATION2 = mASTER_QUALIFICATION2;
	}
	public String getMASTER_QUALIFICATION2_PIC_ORI() {
		return MASTER_QUALIFICATION2_PIC_ORI;
	}
	public void setMASTER_QUALIFICATION2_PIC_ORI(String mASTER_QUALIFICATION2_PIC_ORI) {
		MASTER_QUALIFICATION2_PIC_ORI = mASTER_QUALIFICATION2_PIC_ORI;
	}
	public String getMASTER_QUALIFICATION2_PIC_RE() {
		return MASTER_QUALIFICATION2_PIC_RE;
	}
	public void setMASTER_QUALIFICATION2_PIC_RE(String mASTER_QUALIFICATION2_PIC_RE) {
		MASTER_QUALIFICATION2_PIC_RE = mASTER_QUALIFICATION2_PIC_RE;
	}
	public String getMASTER_QUALIFICATION3() {
		return MASTER_QUALIFICATION3;
	}
	public void setMASTER_QUALIFICATION3(String mASTER_QUALIFICATION3) {
		MASTER_QUALIFICATION3 = mASTER_QUALIFICATION3;
	}
	public String getMASTER_QUALIFICATION3_PIC_ORI() {
		return MASTER_QUALIFICATION3_PIC_ORI;
	}
	public void setMASTER_QUALIFICATION3_PIC_ORI(String mASTER_QUALIFICATION3_PIC_ORI) {
		MASTER_QUALIFICATION3_PIC_ORI = mASTER_QUALIFICATION3_PIC_ORI;
	}
	public String getMASTER_QUALIFICATION3_PIC_RE() {
		return MASTER_QUALIFICATION3_PIC_RE;
	}
	public void setMASTER_QUALIFICATION3_PIC_RE(String mASTER_QUALIFICATION3_PIC_RE) {
		MASTER_QUALIFICATION3_PIC_RE = mASTER_QUALIFICATION3_PIC_RE;
	}
	public String getMASTER_QUALIFICATION4() {
		return MASTER_QUALIFICATION4;
	}
	public void setMASTER_QUALIFICATION4(String mASTER_QUALIFICATION4) {
		MASTER_QUALIFICATION4 = mASTER_QUALIFICATION4;
	}
	public String getMASTER_QUALIFICATION4_PIC_ORI() {
		return MASTER_QUALIFICATION4_PIC_ORI;
	}
	public void setMASTER_QUALIFICATION4_PIC_ORI(String mASTER_QUALIFICATION4_PIC_ORI) {
		MASTER_QUALIFICATION4_PIC_ORI = mASTER_QUALIFICATION4_PIC_ORI;
	}
	public String getMASTER_QUALIFICATION4_PIC_RE() {
		return MASTER_QUALIFICATION4_PIC_RE;
	}
	public void setMASTER_QUALIFICATION4_PIC_RE(String mASTER_QUALIFICATION4_PIC_RE) {
		MASTER_QUALIFICATION4_PIC_RE = mASTER_QUALIFICATION4_PIC_RE;
	}
	public String getMASTER_QUALIFICATION5() {
		return MASTER_QUALIFICATION5;
	}
	public void setMASTER_QUALIFICATION5(String mASTER_QUALIFICATION5) {
		MASTER_QUALIFICATION5 = mASTER_QUALIFICATION5;
	}
	public String getMASTER_QUALIFICATION5_PIC_ORI() {
		return MASTER_QUALIFICATION5_PIC_ORI;
	}
	public void setMASTER_QUALIFICATION5_PIC_ORI(String mASTER_QUALIFICATION5_PIC_ORI) {
		MASTER_QUALIFICATION5_PIC_ORI = mASTER_QUALIFICATION5_PIC_ORI;
	}
	public String getMASTER_QUALIFICATION5_PIC_RE() {
		return MASTER_QUALIFICATION5_PIC_RE;
	}
	public void setMASTER_QUALIFICATION5_PIC_RE(String mASTER_QUALIFICATION5_PIC_RE) {
		MASTER_QUALIFICATION5_PIC_RE = mASTER_QUALIFICATION5_PIC_RE;
	}
	@Override
	public String toString() {
		return "UserMasterQualifcation [USER_EMAIL=" + USER_EMAIL + ", MASTER_QUALIFICATION1=" + MASTER_QUALIFICATION1
				+ ", MASTER_QUALIFICATION1_PIC_ORI=" + MASTER_QUALIFICATION1_PIC_ORI + ", MASTER_QUALIFICATION1_PIC_RE="
				+ MASTER_QUALIFICATION1_PIC_RE + ", MASTER_QUALIFICATION2=" + MASTER_QUALIFICATION2
				+ ", MASTER_QUALIFICATION2_PIC_ORI=" + MASTER_QUALIFICATION2_PIC_ORI + ", MASTER_QUALIFICATION2_PIC_RE="
				+ MASTER_QUALIFICATION2_PIC_RE + ", MASTER_QUALIFICATION3=" + MASTER_QUALIFICATION3
				+ ", MASTER_QUALIFICATION3_PIC_ORI=" + MASTER_QUALIFICATION3_PIC_ORI + ", MASTER_QUALIFICATION3_PIC_RE="
				+ MASTER_QUALIFICATION3_PIC_RE + ", MASTER_QUALIFICATION4=" + MASTER_QUALIFICATION4
				+ ", MASTER_QUALIFICATION4_PIC_ORI=" + MASTER_QUALIFICATION4_PIC_ORI + ", MASTER_QUALIFICATION4_PIC_RE="
				+ MASTER_QUALIFICATION4_PIC_RE + ", MASTER_QUALIFICATION5=" + MASTER_QUALIFICATION5
				+ ", MASTER_QUALIFICATION5_PIC_ORI=" + MASTER_QUALIFICATION5_PIC_ORI + ", MASTER_QUALIFICATION5_PIC_RE="
				+ MASTER_QUALIFICATION5_PIC_RE + "]";
	}
	
	
	
}
